GET https://nxk4dlqm6k.execute-api.us-east-1.amazonaws.com/prod/spaces
###
POST https://nxk4dlqm6k.execute-api.us-east-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "Kenya"
}
###